#!/bin/bash

COMPANY="fp"
SSH_DIR="/home/dev/.ssh"
if [[ $# != 1 ]]
then
        echo "Invalid usage, use $0 env"
        exit 1
fi
if [[ $1 == "winterfell" || $1 == "$COMPANY" ]]
then
        echo "valid environment"
else
        echo "invalid environment"
        exit 1
fi
current_env=$(head -1 $SSH_DIR/config | cut -d ':' -f 2)
if [[ $current_env == $1 ]]
then
        echo "Currently on environment $1, leaving"
        exit 0
else
        echo "Moving to environment $1"
        mv $SSH_DIR/{config,config-$current_env}
        mv $SSH_DIR/{config-$1,config}
        exit 0
fi
